### ISSUE TITLE
A big thank you from Suffolk!

### ISSUE THREAD

**Issue by thomaszwagerman** [DataScienceScotland/sgtemplates#3]
Hi Miles and Nick,

Not an issue - just a note to say thank you.

My name is Thomas Zwagerman, I work as a Data Officer at the Suffolk County Council in England. I was browsing the DataScienceScotland repos for something completely different, when I stumbled on your template. 

I thought it was a great idea, so I have used your work to make a similar template for the Suffolk County Council, in [this repository](https://github.com/SCC-Planning/scctemplate).

I would never have managed to set this up without your work - so I just wanted to acknowledge your work and say thank you for making it open access and documenting it in such a way that others can reuse it and adapt it!

**Comment by miles-drake** [comment]
Hi, Thomas! I apologise for not seeing your kind message earlier. It's great to hear that you were able to use this package as a starting point for your own work! The web pages produced by your `scctemplate` package look fantastic, and I will be taking a closer look at the changes you've made with an eye to improving `sgtemplates`, time permitting.
